# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: postman
    - DOXYFILE: $TRAVIS_BUILD_DIR/doxygen.cfg
    - GH_REPO_REF: github.com/mattumotu/postman.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

language: csharp
solution: Postman.sln

# Generate and deploy documentation
after_success:
  - pwd
  - cd $TRAVIS_BUILD_DIR
  - pwd
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
