# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - master
    - xUnit

# Environment variables
env:
  global:
    - GH_REPO_NAME: postman
    - DOXYFILE: $TRAVIS_BUILD_DIR/doxygen.cfg
    - GH_REPO_REF: github.com/mattumotu/postman.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

language: csharp
solution: Postman.sln
install:
  - nuget restore Postman.sln
  
script:
  - xbuild /p:Configuration=Release Postman.sln
  - mono ./testrunner/xunit.runners.*/tools/xunit.console.clr4.exe ./Postman.Tests/bin/Release/Postman.Tests.dll

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
