# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - master
    - xUnit

# Environment variables
env:
  global:
    - GH_REPO_NAME: postman
    - DOXYFILE: $TRAVIS_BUILD_DIR/doxygen.cfg
    - GH_REPO_REF: github.com/mattumotu/postman.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

language: csharp
solution: Postman.sln
install:
  - nuget restore Postman.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
  
script:
  - xbuild /p:Configuration=Debug Postman.sln
  - pwd
  - ls
  - cd Postman.Tests
  - pwd
  - ls
  - cd bin
  - pwd
  - ls
  - cd Release
  - pwd
  - ls
  #- mono $TRAVIS_BUILD_DIR/packages/xunit.runners.2.1.0/tools/xunit.console.exe $TRAVIS_BUILD_DIR/Postman.Tests/bin/Release/Postman.Tests.dll
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Postman.Tests/bin/Release/Postman.Tests.dll

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
