version: 1.0.{build}

branches:
  only:
  - master
  - appveyor

environment:
  COVERALLS_REPO_TOKEN:
    secure: +rUCy9KXXcle8NAytgkaGdE9kO6vXawtJVMy6QPCjnrWbgjd3lyQ5D9vBh2LDDOr

init:
  - ps: |
      function gitVersion(){
        write-host "This gets the version nr from the end of the git release branch (e.g.: v1.4). And updates the appVersion build version with that (the build nr is appended)."

        $branch=$env:APPVEYOR_REPO_BRANCH
        
        write-host "Branch is $branch"
        $tag=$env:APPVEYOR_REPO_TAG_NAME
        write-host "Tag is $tag"
    
        $posAfterVchar = $branch.LastIndexOf("v") + 1
        $versionLength = $branch.Length - $posAfterVchar
        
        $gitVersion=$branch.substring($posAfterVchar, $versionLength)
        
        $newVersion="$gitVersion.$env:APPVEYOR_BUILD_NUMBER"
        
        write-host "Update appveyor build version to:$newVersion"
        $env:appveyor_build_version="$newVersion"
        appveyor UpdateBuild -Version "$newVersion"
      }
      gitVersion
      
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
configuration: Release

before_build:
- nuget restore Postman.sln
- nuget install xunit.runners -Version 1.9.2 -OutputDirectory tools
- nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
- nuget install coveralls.net -Version 0.412.0 -OutputDirectory tools

build:
  project: Postman.sln
  verbosity: minimal
  publish_nuget: true

test_script:
  - ps: Write-Host "Building version:$env:appveyor_build_version"
  - ps: .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"./tools/xunit.runners.1.9.2/tools/xunit.console.clr4.exe" -targetargs:"./Postman.Tests/bin/$(configuration)/Postman.Tests.dll /noshadow"   -filter:"+[Postman*]*" -output:opencoverCoverage.xml
  - ps: .\tools\coveralls.net.0.412\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
