version: 0.1.0.{build}

branches:
  only:
  - master
  - sonar

environment:
  COVERALLS_REPO_TOKEN:
    secure: +rUCy9KXXcle8NAytgkaGdE9kO6vXawtJVMy6QPCjnrWbgjd3lyQ5D9vBh2LDDOr
  SONAR_TOKEN:
    secure: 9Ox633ZGqoKX65zphEkIsFSwJDivTLE7hAyQ8+iPKNYYMWqWwzrI2+Krxf30IYoM


configuration: Release

init:
  - ps: |
      function updateVersionFromTag(){
        $tag=$env:APPVEYOR_REPO_TAG_NAME
        write-host "Tag is '$tag'"
        if($tag) {
          $posAfterVchar = $tag.LastIndexOf("v") + 1
          $versionLength = $tag.Length - $posAfterVchar

          $gitVersion=$tag.substring($posAfterVchar, $versionLength)

          $newVersion="$gitVersion.$env:APPVEYOR_BUILD_NUMBER"

          write-host "Update appveyor build version to:$newVersion"
          $env:appveyor_build_version="$newVersion"
          appveyor UpdateBuild -Version "$newVersion"
        }
      }
      updateVersionFromTag
  - choco install "msbuild-sonarqube-runner" -y

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
before_build:
- nuget restore src\Postman.sln
- SonarScanner.MSBuild.exe begin /k:"postman" /d:sonar.organization="mattumotu-github" /d:sonar.host.url="https://sonarcloud.io" /d:"sonar.login=c7a1b0c208a442008aa9ef733afb6427dc8c47ff" /d:sonar.cs.opencover.reportsPaths="opencoverCoverage.xml"
 #/d:"sonar.login=$env:sonar_token" /d:"sonar.branch=$env:APPVEYOR_REPO_BRANCH" /d:sonar.cs.opencover.reportsPaths=".\MyProject_coverage.xml" /d:sonar.cs.nunit.reportsPaths="nunitTestResult.xml" /d:"sonar.cpd.exclusions=**/*Tests.cs"  /d:"sonar.language=cs"
build:
  project: src\Postman.sln
  verbosity: minimal
  publish_nuget: true

test_script:
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory tools
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
  - ps: .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"./tools/xunit.runners.1.9.2/tools/xunit.console.clr4.exe" -targetargs:"src/Postman.Tests/bin/$env:CONFIGURATION/Postman.Tests.dll /noshadow"   -filter:"+[Postman*]*" -output:opencoverCoverage.xml
  - nuget install coveralls.net -Version 0.412.0 -OutputDirectory tools
  - ps: .\tools\coveralls.net.0.412\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor

after_test:
  - SonarScanner.MSBuild.exe end /d:sonar.login="c7a1b0c208a442008aa9ef733afb6427dc8c47ff"

deploy:
  - provider: NuGet
    api_key:
      secure: rU0RM/K3kY0g80VVfmvE4BwPCrhLiiohnaRMog4fYuO7W1IJsPqA3VP4zxapdD4Q
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true
